### ISSUE TITLE
[Question] - How to map volume to share laravel code?

### ISSUE THREAD

**Issue by linktoahref** [laravel-fans/laravel-docker#60]
Hi,

I am trying to build the image using the docker-compose file as follows:

```yml
name: "laravel_app"
services:
    web:
      image: "laravelfans/laravel"
      env_file: local.env
      ports:
          - 80:80
      volumes:
          - .:/var/www/laravel
```

Contents of local.env as follows:

```
APP_ENV=local
APP_KEY=base64:L+3avOYCfuq8nnDpHs74+5Et3sx27TssucHQIyqfpDY=
DB_CONNECTION=sqlite
```

After building the status is showing as `Exited (1)`. Upon checking the logs, it states:

> chown: cannot access 'bootstrap/cache': No such file or directory

I tried to create the following directories in the host environment:
- bootstrap/cache
- storage/
- database/database.sqlite

However, that fails on 

> Could not open input file: artisan

How to share the laravel code between the container and the host?

Similar question on StackOverflow: https://stackoverflow.com/questions/78003215/docker-volume-to-share-php-code-between-container-and-local-for-development-usin

Thanks.

**Comment by linktoahref** [comment]
I removed the volume mappings and built the image using:

```yaml
name: "laravel_app"
services:
    web:
      image: "laravelfans/laravel"
      env_file: local.env
      ports:
          - 80:80
```

Then copied the contents of the container into the host using the docker `cp` command

```
docker cp <containerId>:/var/www/laravel .
```

Moved the contents within the laravel directory in the host to the appropriate location

Updated the `docker-compose.yaml` file

```yaml
name: "laravel_app"
services:
    web:
      image: "laravelfans/laravel"
      env_file: local.env
      ports:
          - 80:80
      volumes:
          - .:/var/www/laravel
          - /var/www/laravel/vendor
```

Stopped, destroyed and rebuilt the container using the above definition and the application was served without any `Exited (1)` error from the container.
